"""Update device settings table

Revision ID: 5e2c4cdd8cc8
Revises: 04b75922e160
Create Date: 2025-12-08 18:36:00.669377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2c4cdd8cc8'
down_revision: Union[str, Sequence[str], None] = '04b75922e160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'app_settings', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_settings', type_='unique')
    # ### end Alembic commands ###
