"""Add some security features

Revision ID: 6a369184c1fd
Revises: 8a460fbd0992
Create Date: 2026-04-19 20:06:40.395924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a369184c1fd'
down_revision: Union[str, Sequence[str], None] = '8a460fbd0992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_codes', ['id'])
    op.create_unique_constraint(None, 'password_reset_sessions', ['id'])
    op.create_unique_constraint(None, 'recovery_codes', ['id'])
    op.add_column('tokens', sa.Column('access_jti_hash', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_tokens_access_jti_hash'), 'tokens', ['access_jti_hash'], unique=False)
    op.create_index(op.f('ix_tokens_token_hash'), 'tokens', ['token_hash'], unique=False)
    op.drop_column('tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tokens_token_hash'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_access_jti_hash'), table_name='tokens')
    op.drop_column('tokens', 'access_jti_hash')
    op.drop_constraint(None, 'recovery_codes', type_='unique')
    op.drop_constraint(None, 'password_reset_sessions', type_='unique')
    op.drop_constraint(None, 'email_codes', type_='unique')
    # ### end Alembic commands ###
