"""Add avatar key to users

Revision ID: 6ad9aab0d05f
Revises: 5e2c4cdd8cc8
Create Date: 2026-03-12 15:02:21.680871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad9aab0d05f'
down_revision: Union[str, Sequence[str], None] = '5e2c4cdd8cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', sa.String(length=265), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###
