"""Add client identity tables

Revision ID: 7644fd5cfa6f
Revises: 6a369184c1fd
Create Date: 2026-04-30 19:14:28.985195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7644fd5cfa6f'
down_revision: Union[str, Sequence[str], None] = '6a369184c1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('public_key_der', sa.LargeBinary(), nullable=False),
    sa.Column('public_key_sha256', sa.String(length=64), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('signing_cert_sha256', sa.String(length=95), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('attestation_security_level', sa.String(length=32), nullable=True),
    sa.Column('verified_boot_state', sa.String(length=32), nullable=True),
    sa.Column('device_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_instances_key_id'), 'client_instances', ['key_id'], unique=True)
    op.create_index(op.f('ix_client_instances_public_key_sha256'), 'client_instances', ['public_key_sha256'], unique=True)
    op.create_table('client_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_instance_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_instance_id'], ['client_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_sessions_client_instance_id'), 'client_sessions', ['client_instance_id'], unique=False)
    op.create_index(op.f('ix_client_sessions_session_token_hash'), 'client_sessions', ['session_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_sessions_session_token_hash'), table_name='client_sessions')
    op.drop_index(op.f('ix_client_sessions_client_instance_id'), table_name='client_sessions')
    op.drop_table('client_sessions')
    op.drop_index(op.f('ix_client_instances_public_key_sha256'), table_name='client_instances')
    op.drop_index(op.f('ix_client_instances_key_id'), table_name='client_instances')
    op.drop_table('client_instances')
    # ### end Alembic commands ###
