"""Add: App settings

Revision ID: ad2c2b4b9a91
Revises: 93872e4eb7bc
Create Date: 2025-11-10 20:26:46.040824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2c2b4b9a91'
down_revision: Union[str, Sequence[str], None] = '93872e4eb7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device_settings', ['id'])
    op.create_unique_constraint(None, 'devices', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'device_settings', type_='unique')
    # ### end Alembic commands ###
